# general
batch_size: 128
input_size: 112
embd_shape: 512
sub_name: 'arc_res50_2n' # 'arc_res50_2n', 'arc_mbv2_2n'
backbone_type: 'ResNet50' # 'ResNet50', 'MobileNetV2'
head_type: ArcHead
is_ccrop: False # central-cropping or not

# train
train_dataset: './data/2n_bin.tfrecord'
binary_img: True
num_classes: 800
num_samples: 52618
epochs: 50
base_lr: 0.0001
w_decay: !!float 5e-4
save_steps: 4110 # 52618 // 128 * 10

# test
test_dataset: 'data/kface_test_2n_npy'