# general
batch_size: 128
input_size: 112
embd_shape: 512
sub_name: 'arc_mbv2'
backbone_type: 'ResNet50' # 'ResNet50', 'MobileNetV2'
head_type: ArcHead
is_ccrop: False # central-cropping or not

# train
train_dataset: './data/masked_bin.tfrecord'
binary_img: True
num_classes: 400
num_samples: 7600
epochs: 50
base_lr: 0.0001
w_decay: !!float 5e-4
save_steps: 590 # 7600 // 128 * 10

# test
test_dataset: 'data/kface_test_npy'