# general
input_shape: (224, 224, 3)

batch_size: 32
embd_shape: 512
is_ccrop: False # central-cropping or not

# train
train_dataset: ''
binary_img: True
num_classes: 800
num_samples: 000000000
epochs: 5
lr: 0.001
w_decay: !!float 5e-4
save_steps: 1000

# test
test_dataset: ''